name: vercel-pr-deploy-prune

# Controls when the action will run. Triggers the workflow on push
# events but only for the develop branch
on:
  pull_request:
    types: [ closed ]

jobs:
  vercel-deploy-prune:
    steps:

    - name: Make some more metadata available as variables
      id: metadata
      run: |
        echo "::set-output name=DEPLOY_NAME::PR-$(echo $GITHUB_REF | awk -F/ '{ print $3 }')"

    - name: mark environment as deactivated
      uses: bobheadxi/deployments@v0.6.2
      with:
        step: deactivate-env
        token: ${{ secrets.GITHUB_TOKEN }}
        env: vercel-deploy-${{ steps.metadata.outputs.DEPLOY_NAME }}
        desc: Deployment vercel-deploy-${{ steps.metadata.outputs.DEPLOY_NAME }} was pruned
